export const DEPOSIT = 'DEPOSIT';
export const WITHDRAW = 'WITHDRAW';

export const ASYNC_ACTION_START = 'ASYNC_ACTION_START';
export const ASYNC_ACTION_FAIL = 'ASYNC_ACTION_FAIL';

export const FETCH_NOTES_SUCCESS = 'FETCH_NOTES_SUCCESS';
export const DELETE_NOTE_SUCCESS = 'DELETE_NOTE_SUCCESS';
export const ADD_NOTE_SUCCESS = 'ADD_NOTE_SUCCESS';

// export const FETCH_NOTES = 'FETCH_NOTES';
// export const DELETE_NOTE = 'DELETE_NOTE';
